#!groovy
//********************************************************************************************                                                        
//	  ______                                __                ________  __       __ 
//	 /      \                              |  \              |        \|  \     /  \
//	|  $$$$$$\  ______   ______    _______ | $$____          | $$$$$$$$| $$\   /  $$
//	| $$__| $$ /      \ |      \  /       \| $$    \  ______ | $$__    | $$$\ /  $$$
//	| $$    $$|  $$$$$$\ \$$$$$$\|  $$$$$$$| $$$$$$$\|      \| $$  \   | $$$$\  $$$$
//	| $$$$$$$$| $$   \$$/      $$ \$$    \ | $$  | $$ \$$$$$$| $$$$$   | $$\$$ $$ $$
//	| $$  | $$| $$     |  $$$$$$$ _\$$$$$$\| $$  | $$        | $$_____ | $$ \$$$| $$
//	| $$  | $$| $$      \$$    $$|       $$| $$  | $$        | $$     \| $$  \$ | $$
//	 \$$   \$$ \$$       \$$$$$$$ \$$$$$$$  \$$   \$$         \$$$$$$$$ \$$      \$$
//	                                                                                
//	                                                                                
//	                        
//********************************************************************************************
pipeline{
    agent none 
    stages{
        stage('checkout'){
            agent {
                label 'master'
            }
            steps {
				checkout([$class: 'GitSCM',
					branches: [[name: '*/master']],
					extensions: [[$class: 'CloneOption', timeout: 120]],
					gitTool: 'Default', 
					userRemoteConfigs: [[url: 'https://github.com/ArashEM/EPCI.git']]
				])
                stash includes: 'FW/sources/**', name: 'firmware-src'
            }
        }
		stage('parallel build')
		{
			parallel {
				stage('build'){
					agent {
						label 'dh-01'
					}
					steps {
						unstash 'firmware-src'
						dir('FW/sources/driver'){
							sh 'make clean'
							sh 'make'
						}
					}
					post {
						success {
							archiveArtifacts 'FW/sources/driver/build/*.ko'
							stash includes:  'FW/sources/driver/build/*.ko', name: 'kernel-object'
						}
						cleanup {
							cleanWs()
						}
					}
					
				}
			
				stage('synthesis') {
					agent {
						label 'ise-01'
					}
					steps {
						unstash 'firmware-src'
						dir('FW/sources/hdl'){
							sh 'make clean'
							sh 'make mcs'
						}
					}
					post {
						success {
							archiveArtifacts '/FW/sources/hdl/build/*.bit'
							stash includes:   'FW/sources/hdl/build/*.bit', name: 'bitfile'
							archiveArtifacts '/FW/sources/hdl/build/*.mcs'
						}
						cleanup {
							cleanWs()
						}
					}
				}
			}
        }
		stage('deploy')
		{
			agent {
                label 'dh-01'
            }
            steps {
				unstash 'firmware-src'
				unstash 'bitfile'
				unstash 'kernel-object'
				dir('FW/sources/hdl') {
					sh 'sudo openocd -f scripts/epci-openocd.cfg'
					sh 'sudo ./scripts/epci_configure'
				}
				dir('FW/sources/driver') {
					sh 'sudo ./scripts/epci_load'
				}
			}
		}
    }
    
}