#!/bin/sh
module="epci"
vid="10ee"
did="0600"
cmd="0x0002"

# Resolve Address
address=$(lspci -d $vid:$did | cut -d" " -f1)

# Resolve memory area
bar0=$(grep "0000:$address" /proc/iomem | cut -d"-" -f1 | xargs)

#set BAR0 after board is prgrammed
setpci -s $address BASE_ADDRESS_0=0x$bar0

#enable memory region
setpci -s $address COMMAND=$cmd

